#!/usr/bin/env python3
"""Curate VFX sprites into assets/vfx/ (512x512 RGBA PNG), write MANIFEST.json + contact sheet."""
import os, json, math
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

SRC = "/home/user/tools/vfx_src"
KP = os.path.join(SRC, "kenney_particle-pack/PNG (Transparent)")
KS = os.path.join(SRC, "kenney_smoke-particles/PNG")
OUT = "/home/user/New/steal-a-kaiju/assets/vfx"
SIZE = 512
os.makedirs(OUT, exist_ok=True)

KENNEY_PP = {"source": "https://kenney.nl/assets/particle-pack", "pack": "Kenney Particle Pack 1.1", "license": "CC0 1.0", "attribution": "Kenney (www.kenney.nl)"}
KENNEY_SM = {"source": "https://kenney.nl/assets/smoke-particles", "pack": "Kenney Smoke Particles", "license": "CC0 1.0", "attribution": "Kenney (www.kenney.nl)"}
GEN = {"source": "generated by tools/models/curate_vfx.py (this repository)", "pack": "procedural", "license": "CC0 1.0", "attribution": "none required"}

# key -> (source pack, relative file)
PICK = {
    "spark": (KP, "spark_01.png", KENNEY_PP),
    "flare": (KP, "flare_01.png", KENNEY_PP),
    "glow_soft": (KP, "circle_05.png", KENNEY_PP),
    "glow_hard": (KP, "light_02.png", KENNEY_PP),
    "smoke": (KS, "White puff/whitePuff04.png", KENNEY_SM),
    "fire": (KP, "flame_05.png", KENNEY_PP),
    "star4": (KP, "star_06.png", KENNEY_PP),
    "star5": (KP, "symbol_02.png", KENNEY_PP),
    "sparkle": (KP, "star_08.png", KENNEY_PP),
    "ring": (KP, "circle_02.png", KENNEY_PP),
    "shockwave": (KP, "circle_03.png", KENNEY_PP),
    "lightning": (KP, "spark_05.png", KENNEY_PP),
    "magic": (KP, "magic_03.png", KENNEY_PP),
    "twirl": (KP, "twirl_02.png", KENNEY_PP),
    "scorch": (KP, "scorch_01.png", KENNEY_PP),
    "dust": (KP, "smoke_06.png", KENNEY_PP),
    "heart": (KP, "symbol_01.png", KENNEY_PP),
    "muzzle": (KP, "muzzle_01.png", KENNEY_PP),
    "trail": (KP, "trace_06.png", KENNEY_PP),
    "slash": (KP, "slash_03.png", KENNEY_PP),
    "meteor_trail": (KP, "trace_04.png", KENNEY_PP),
    "cloud": (KS, "White puff/whitePuff15.png", KENNEY_SM),
}


def square(im):
    im = im.convert("RGBA")
    w, h = im.size
    s = max(w, h)
    canvas = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    canvas.paste(im, ((s - w) // 2, (s - h) // 2))
    if s != SIZE:
        canvas = canvas.resize((SIZE, SIZE), Image.LANCZOS)
    return canvas


def to_white_alpha(im):
    """Force RGB to white (alpha carries the shape) so ParticleEmitter.Color tints cleanly."""
    arr = np.asarray(im).copy()
    arr[:, :, :3] = 255
    return Image.fromarray(arr, "RGBA")


# ---------- procedural sprites ----------
def new():
    return Image.new("RGBA", (SIZE * 2, SIZE * 2), (0, 0, 0, 0))


def finish(im, blur=1.2):
    im = im.resize((SIZE, SIZE), Image.LANCZOS)
    if blur:
        a = im.split()[3].filter(ImageFilter.GaussianBlur(blur))
        im.putalpha(a)
    return im


def gen_circle():
    im = new(); d = ImageDraw.Draw(im)
    d.ellipse([80, 80, SIZE * 2 - 80, SIZE * 2 - 80], fill=(255, 255, 255, 255))
    return finish(im)


def gen_bubble():
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2
    # faint fill, strong rim, highlight
    d.ellipse([90, 90, S - 90, S - 90], fill=(255, 255, 255, 60))
    d.ellipse([90, 90, S - 90, S - 90], outline=(255, 255, 255, 255), width=28)
    d.ellipse([200, 160, 420, 330], fill=(255, 255, 255, 230))
    d.ellipse([260, 360, 330, 430], fill=(255, 255, 255, 180))
    return finish(im, 1.5)


def gen_skull():
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2; W = (255, 255, 255, 255); T = (0, 0, 0, 0)
    d.ellipse([S * 0.2, S * 0.1, S * 0.8, S * 0.7], fill=W)          # cranium
    d.rounded_rectangle([S * 0.33, S * 0.55, S * 0.67, S * 0.86], radius=60, fill=W)  # jaw
    d.ellipse([S * 0.3, S * 0.36, S * 0.46, S * 0.55], fill=T)        # eyes
    d.ellipse([S * 0.54, S * 0.36, S * 0.7, S * 0.55], fill=T)
    d.polygon([(S * 0.5, S * 0.56), (S * 0.45, S * 0.66), (S * 0.55, S * 0.66)], fill=T)  # nose
    for i in range(4):                                                  # teeth gaps
        x = S * 0.38 + i * S * 0.065
        d.rectangle([x, S * 0.76, x + 12, S * 0.86], fill=T)
    return finish(im, 1.0)


def gen_confetti():
    rng = np.random.default_rng(7)
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2
    cols = [(255, 80, 120), (255, 210, 60), (80, 220, 140), (80, 160, 255), (200, 120, 255), (255, 255, 255)]
    for _ in range(38):
        cx, cy = rng.uniform(S * 0.1, S * 0.9, 2)
        w, h = rng.uniform(40, 90), rng.uniform(70, 150)
        ang = rng.uniform(0, math.pi)
        c = cols[rng.integers(len(cols))]
        pts = []
        for dx, dy in [(-w / 2, -h / 2), (w / 2, -h / 2), (w / 2, h / 2), (-w / 2, h / 2)]:
            pts.append((cx + dx * math.cos(ang) - dy * math.sin(ang), cy + dx * math.sin(ang) + dy * math.cos(ang)))
        d.polygon(pts, fill=c + (255,))
    return finish(im, 0.8)


def gen_radioactive():
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2; c = S / 2; W = (255, 255, 255, 255)
    d.ellipse([c - S * 0.44, c - S * 0.44, c + S * 0.44, c + S * 0.44], fill=(255, 255, 255, 70))
    for k in range(3):
        a0 = 90 + k * 120 - 30
        d.pieslice([c - S * 0.4, c - S * 0.4, c + S * 0.4, c + S * 0.4], a0, a0 + 60, fill=W)
    d.ellipse([c - S * 0.13, c - S * 0.13, c + S * 0.13, c + S * 0.13], fill=(0, 0, 0, 0))
    d.ellipse([c - S * 0.07, c - S * 0.07, c + S * 0.07, c + S * 0.07], fill=W)
    return finish(im, 1.0)


def gen_drip():
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2; W = (255, 255, 255, 255)
    d.ellipse([S * 0.25, S * 0.42, S * 0.75, S * 0.92], fill=W)
    d.polygon([(S * 0.5, S * 0.06), (S * 0.26, S * 0.66), (S * 0.74, S * 0.66)], fill=W)
    d.ellipse([S * 0.36, S * 0.55, S * 0.46, S * 0.7], fill=(255, 255, 255, 120))
    return finish(im, 1.2)


def gen_bolt():
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2
    pts = [(0.62, 0.04), (0.28, 0.54), (0.48, 0.54), (0.36, 0.96), (0.74, 0.42), (0.54, 0.42)]
    d.polygon([(x * S, y * S) for x, y in pts], fill=(255, 255, 255, 255))
    glow = im.filter(ImageFilter.GaussianBlur(40))
    g = np.asarray(glow).copy(); g[:, :, 3] = (g[:, :, 3] * 0.6).astype(np.uint8)
    out = Image.alpha_composite(Image.fromarray(g, "RGBA"), im)
    return finish(out, 0.8)


def gen_leaf():
    im = new(); d = ImageDraw.Draw(im)
    S = SIZE * 2; W = (255, 255, 255, 255)
    # leaf = two arcs
    pts = []
    for i in range(80):
        t = i / 79
        x = S * (0.15 + 0.7 * t); y = S * 0.5 - math.sin(t * math.pi) * S * 0.28
        pts.append((x, y))
    for i in range(80):
        t = 1 - i / 79
        x = S * (0.15 + 0.7 * t); y = S * 0.5 + math.sin(t * math.pi) * S * 0.28
        pts.append((x, y))
    d.polygon(pts, fill=W)
    d.line([(S * 0.2, S * 0.5), (S * 0.82, S * 0.5)], fill=(0, 0, 0, 0), width=14)
    for i in range(1, 6):
        x = S * (0.25 + i * 0.1)
        d.line([(x, S * 0.5), (x + S * 0.08, S * 0.5 - S * 0.16)], fill=(0, 0, 0, 0), width=8)
        d.line([(x, S * 0.5), (x + S * 0.08, S * 0.5 + S * 0.16)], fill=(0, 0, 0, 0), width=8)
    d.line([(S * 0.05, S * 0.62), (S * 0.2, S * 0.5)], fill=W, width=22)  # stem
    return finish(im, 1.0)


GENERATED = {
    "circle": (gen_circle, "solid antialiased disc"),
    "bubble": (gen_bubble, "bubble with rim + highlight"),
    "skull": (gen_skull, "cartoon skull silhouette"),
    "confetti": (gen_confetti, "coloured confetti pieces (not tintable: keep Color white)"),
    "radioactive": (gen_radioactive, "trefoil symbol"),
    "drip": (gen_drip, "droplet"),
    "bolt": (gen_bolt, "cartoon zigzag lightning bolt with glow"),
    "leaf": (gen_leaf, "leaf silhouette with veins"),
}

ORDER = ["spark", "flare", "glow_soft", "glow_hard", "smoke", "fire", "star4", "star5", "sparkle", "circle", "ring", "shockwave", "lightning", "magic", "twirl", "scorch", "dust", "bubble", "heart", "skull", "muzzle", "trail", "slash", "confetti", "meteor_trail", "radioactive", "drip", "bolt", "cloud", "leaf"]

manifest = {}
for key in ORDER:
    dst = os.path.join(OUT, key + ".png")
    if key in PICK:
        base, rel, meta = PICK[key]
        im = square(Image.open(os.path.join(base, rel)))
        im = to_white_alpha(im)
        im.save(dst, optimize=True)
        manifest[key] = {"file": key + ".png", "originalFile": rel, **meta, "size": SIZE}
    else:
        fn, desc = GENERATED[key]
        im = fn()
        im.save(dst, optimize=True)
        manifest[key] = {"file": key + ".png", "originalFile": None, **GEN, "notes": desc, "size": SIZE}
    print(key, os.path.getsize(dst))

json.dump(manifest, open(os.path.join(OUT, "MANIFEST.json"), "w"), indent=2)

# contact sheet
cell, cols = 160, 6
rows = math.ceil(len(ORDER) / cols)
font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 15)
sheet = Image.new("RGB", (cols * cell, rows * (cell + 24)), (16, 16, 24))
for i, key in enumerate(ORDER):
    im = Image.open(os.path.join(OUT, key + ".png")).convert("RGBA").resize((cell - 12, cell - 12), Image.LANCZOS)
    x, y = (i % cols) * cell, (i // cols) * (cell + 24)
    sheet.paste(im, (x + 6, y + 6), im)
    ImageDraw.Draw(sheet).text((x + 8, y + cell + 2), key, fill=(235, 235, 240), font=font)
sheet.save(os.path.join(OUT, "contact_sheet.png"))
print("sheet", sheet.size)
